src/Entity/Signature.php
<?php

namespace App\Entity;

use App\Repository\SignatureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SignatureRepository::class)]
class Signature
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    private ?string $organization = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    private ?string $zipCode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\ManyToOne]
    private ?Logo $logo = null;

    #[ORM\ManyToOne]
    private ?Logo $logo_2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $disclaimer = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $facebook = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $youtube = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $unsa = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $linkedin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $twitter = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updateAt = null;

    #[ORM\Column]
    private ?int $userId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getOrganization(): ?string
    {
        return $this->organization;
    }

    public function setOrganization(string $organization): static
    {
        $this->organization = $organization;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): static
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getLogo(): ?Logo
    {
        return $this->logo;
    }

    public function setLogo(?Logo $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getLogo2(): ?Logo
    {
        return $this->logo_2;
    }

    public function setLogo2(?Logo $logo_2): static
    {
        $this->logo_2 = $logo_2;

        return $this;
    }

    public function getDisclaimer(): ?string
    {
        return $this->disclaimer;
    }

    public function setDisclaimer(?string $disclaimer): static
    {
        $this->disclaimer = $disclaimer;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): static
    {
        $this->facebook = $facebook;
        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): static
    {
        $this->youtube = $youtube;
        return $this;
    }

    public function getUnsa(): ?string
    {
        return $this->unsa;
    }

    public function setUnsa(?string $unsa): static
    {
        $this->unsa = $unsa;
        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): static
    {
        $this->linkedin = $linkedin;
        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): static
    {
        $this->twitter = $twitter;
        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeImmutable $createAt): static
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeImmutable $updateAt): static
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->userId;
    }

    public function setUserId(int $userId): static
    {
        $this->userId = $userId;

        return $this;
    }
}

templates/signature/edit_signature.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la signature
{% endblock %}

{% block body %}

	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6">
				<section class="view_signature d-flex justify-content-center align-items-center mt-5">
					<div class=" p-3">
						<table border="0" cellpadding="0" width="480">
							<tbody>
								<tr>
									<td align="left" valign="middle" width="10">
											<p style="padding-inline-end: 10px;font-size: 12px;line-height: 14px;">
											<a href="https://www.unsa.org/"><img id="logo" src="https://lab-web.unsa.org/signature{{signature.logo.path}}" class="border-0" style="border: none;inline-size: 120px;" alt=""></a>
										</p>
									</td>
									<td><br>
										<p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;font-size: 12px; line-height: 14px; color: #000;text-align: start;">
											<span id="name" class="font-weight-bold" style="color: #000;font-weight: bold;font-size: 14px;">
												{% set name = signature.name|split('&') %}
												{{name[0]}} {{name[1]}}
											</span><br>
											<span id="role" style="color: #666;">
												<i>{{signature.role}}</i>
											</span><br>
											<span id="organization" style="color: #666;">
												<i>{{signature.organization}}</i>
											</span><br>
										</p>
										<p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;font-size: 12px; line-height: 14px; color: #000;">
											<span id="address" style="color: #000;">{{signature.adress}}</span><br>
											<span id="zipCode" style="color: #000;">{{signature.zipCode}}&nbsp;</span>
											<span id="city" style="color: #000;">{{signature.city}}
											</span><br>
										</p>
										<p style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;font-size: 12px; line-height: 14px; color: #000;">
											<img src="https://lab-web.unsa.org/signature/img/Application/mail.png" class="border-0" style="border: none;block-size: 12px;margin-inline-end: .5em;">
											<a id="previewEmail" href="mailto:${email}" style="color: #666; font-style: italic;">{{signature.email}}</a><br>
											<img src="https://lab-web.unsa.org/signature/img/Application/phone.png" class="border-0" style="border: none;block-size: 14px;margin-inline-end: .5em;">
											<span id="phone" style="color: #666;">{{signature.phone}}</span>
										</p>
										{% if signature.logo2 is not null %}
											<td align="right" valign="middle" width="10">
												<p style="padding-inline-end: 10px; font-size: 12px; line-height: 14px;">
													<a href="https://unsa.org/"><img alt="" id="logo_2" src="https://lab-web.unsa.org/signature{{signature.logo2.path}}" style="border: none; inline-size: 120px;"></a>
												</p>
											</td>
										{% endif %}
									</td>
								</tr>
							</tbody>
						</table>
						
					</div>
				</section><br>
			</div>
			<div class="col-lg-6">
				<section class="generate_signature d-flex justify-content-center align-items-center">
					<form class="form" method="post" name="form">
						{{ form_start(form) }}

						<div class="form-row">
							<div class="col">
								<div class="form-group">
									{{ form_row(form.last_name, {'attr': {'class': 'form-control', 'id': 'form_last_name', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									{{ form_row(form.first_name, {'attr': {'class': 'form-control', 'id': 'form_first_name', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
						</div>

						<div class="form-row">
							<div class="col">
								<div class="form-group">
									{{ form_row(form.phone_landline, {'attr': {'class': 'form-control', 'id': 'form_phone_landline', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									{{ form_row(form.phone_mobile, {'attr': {'class': 'form-control', 'id': 'form_phone_mobile', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
						</div>

						<div class="form-group">
							{{ form_row(form.email, {'attr': {'class': 'form-control', 'id': 'form_email', 'oninput': 'updatePreview()'}}) }}
						</div>

						<div class="form-row">
							<div class="col">
								<div class="form-group">
									{{ form_row(form.organization, {'attr': {'class': 'form-control', 'id': 'form_organization', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									{{ form_row(form.role, {'attr': {'class': 'form-control', 'id': 'form_role', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
						</div>


						<div class="form-group">
							{{ form_row(form.adress, {'attr': {'class': 'form-control', 'id': 'form_address', 'oninput': 'updatePreview()'}}) }}
						</div>


						<div class="form-row">
							<div class="col">
								<div class="form-group">
									{{ form_row(form.zip_code, {'attr': {'class': 'form-control', 'id': 'form_zip_code', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									{{ form_row(form.city, {'attr': {'class': 'form-control', 'id': 'form_city', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>
						</div>
						
						<div class="form-row">
							<div class="col">
								 <div class="form-group">
									{{ form_row(form.logo, {'attr': {'class': 'form-control', 'id': 'form_logo', 'oninput': 'updatePreview()','required': 'required'}}) }}
								</div>
							</div>

							<div class="col">
								 <div class="form-group">
									{{ form_row(form.logo_2, {'attr': {'class': 'form-control', 'id': 'f', 'oninput': 'updatePreview()'}}) }}
								</div>
							</div>

						</div>

						<div class="form-row">								
							<div class="col"><br>
								{{form_row(form.unsa,{'attr': {'id':'unsa', 'class': 'hidden-unsa'}})}}<br>
								{{form_row(form.linkedin,{'attr': {'id':'linkedin', 'class': 'hidden-linkedin'}})}}
							</div>
							<div class="col"><br>
								{{ form_row(form.facebook, {'attr': {'id': 'facebook', 'class': 'hidden-facebook'}}) }}<br>
								{{form_row(form.youtube,{'attr': {'id':'youtube', 'class': 'hidden-youtube'}})}}
							</div>
							<div class="col-md-6"><br>
								{{form_row(form.twitter,{'attr': {'id':'twitter', 'class': 'hidden-twitter'}})}}
							</div>
						</div><br>

						
						<p>Merci de bien vouloir renseignez tout les champs obligatoire <br>contenant une astérix (*).</p>

						{{ form_end(form) }}<br>
					</form>
				</section>
			</div>
		</div>
	</div>
<script>
	document.querySelector('form[name="form"]').addEventListener('submit', function(event) {
		event.preventDefault();
		var form = event.target;

		var formData = new FormData(form);

		var xhr = new XMLHttpRequest();
		xhr.open(form.method, form.action);
		xhr.onreadystatechange = function() {
			if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
				var parentWindow = window.parent;
				parentWindow.postMessage('closeModal', '*');
			}
		};
		xhr.send(formData);
	});

</script>

{% endblock %}